<html>
          <head></head>
          <body>
            <h2>Execution Error for Pull Request at ciuser/arbitrary</h2>
<p>A repository monitored by the Continuous Integration server has
  just died because of an *unhandled exception* in the CI server
  code.</p>
<p>
  <h3><a href="http://github.com/ciuser/arbitrary">ciuser/arbitrary</a> <a href="__pullurl__">#__pullnum__</a></h3>
  Unit testing description of arbitrary.
</p>
<h2>Error Message and Stack Trace</h2>

__message__

<p>
Unit tests are configured to run in "/Users/trunks/codes/ci/tests/repo".</p>
<p>If you have any questions, please contact the owner of the repository:</p>
<p>
  <a href="http://usercontent.github.com/ciuser">ciuser</a><br />
  <a href="mailto:__useremail">ciuser@gmail.com</a>
</p>
<p>
Kind Regards,<br />
CI Bot
</p>
  
          </body>
        </html>